version: 0.0
os: linux
run-as: root
files:  
  - source: /
    destination: /home/ubuntu/backend/
    timeout: 300
    
hooks:
  ApplicationStop: 
    - location: script/stop_server.sh
      timeout: 300
      run-as: root
  Install:
    - location: script/Install.sh
      timeout: 300
      run-as: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      run-as: root
  
 
           
