version: 0.0
os: linux
files:  
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall: 
    - location: script/dependencies.sh
      timeout: 300
      runas: root
  Install: 
    - runas: root     
  AfterInstall: 
    - location: script/postInstall.sh 
      timeout: 300
      runas: root
