version: 0.0
os: linux
files:  
  - source: /
    destination: /home/ubuntu/backend
hooks:
  BeforeInstall: 
    - location: /dependencies.sh
      timeout: 300
      runas: root
  Install: 
    - runas: root     
  AfterInstall: 
    - location: /postInstall.sh 
      timeout: 300
      runas: root
