version: 0.0
os: linux
run-as: root
files:  
  - source: /
    destination: /home/ubuntu/backend/
    timeout: 300
    
hooks:
  BeforeInstall:
    - location: script/Install_Dependencies.sh
      timeout: 300
      run-as: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      run-as: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      run-as: root
           
