version: 0.2

phases: 
  pre_build: 
    command: 
      - echo entered in prebuild phase     

  build: 
    command: 
      - echo entered into build phase
      - sed -i 's/localhost/172.31.81.57:27017,172.31.84.79:27017,172.31.91.74:27017/' app.js
      - cat app.js
  post_build: 
    command: 
      - echo entered in post build stage     

artifacts: 
  files: 
    - '**/*'
